library("locfit");
dat <- read.table("rsgibbs_locfit.dat", header=TRUE);
fit <- locfit::locfit(w~m, data=dat);
result <- predict(fit, dat[,"m"]);
dat$locfit <- result;
fit <- locfit::locfit.raw(x=dat$m, y=dat$w, family="gamma");
result <- predict(fit, dat[,"m"]);
dat$gamma <- result;
fit <- locfit::locfit.raw(x=dat$m, y=dat$w, family="gaussian");
result <- predict(fit, dat[,"m"]);
dat$gaussian <- result;
fit <- locfit::locfit.raw(x=dat$m, y=dat$w, family="geom");
result <- predict(fit, dat[,"m"]);
dat$geom <- result;
fit <- locfit::locfit.raw(x=dat$m, y=dat$w, family="poisson");
result <- predict(fit, dat[,"m"]);
dat$poisson <- result;
finalfit <- fit;
output <- file("rsgibbs_locfit.dat", "w");
write.table(dat, output, append=FALSE, sep="\t", row.names=FALSE, col.names=FALSE);
flush(output);
close(output);
dat <- read.table("rsgibbs_predict.dat", header=TRUE);
result <- predict(finalfit, dat[,"m"]);
dat$w <- result;
output <- file("rsgibbs_predict.dat", "w");
write.table(dat, output, append=FALSE, sep="\t", row.names=FALSE, col.names=FALSE);
flush(output);
close(output);