library("locfit");
dat <- read.table("rsgibbs_locfit.dat", header=TRUE);
fit <- locfit::locfit.raw(x=dat$m, y=dat$w, family="poisson");
result <- predict(fit, dat[,"m"]);
dat$poisson <- result;
output <- file("rsgibbs_locfit.dat", "w");
write.table(dat, output, append=FALSE, sep="\t", row.names=FALSE, col.names=FALSE);
flush(output);
close(output);
dat <- read.table("rsgibbs_predict.dat", header=TRUE);
result <- predict(fit, dat[,"m"]);
dat$w <- result;
output <- file("rsgibbs_predict.dat", "w");
write.table(dat, output, append=FALSE, sep="\t", row.names=FALSE, col.names=FALSE);
flush(output);
close(output);